version: '3'
services:
  flask:
    build: 
      context: .
      dockerfile: Dockerfile_python
    container_name: flask_container
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "5050:5050"
  vue:
    build:
      context: .
      dockerfile: Dockerfile_node
    image: vue_img
    container_name: vue_container
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"